server:
  port: 9094
#  servlet:
#    context-path: /serverclient #如果不加这个项目名 单独访问的时间就不要加项目名，http://localhost:9094/face/test，如果做ribbon负载均衡不能加项目名
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/  # 服务中心地址
spring:
  application:
    name: serverclient # 客户端的名字
    
  datasource:
    username: root
    password: TQrGHEKTmPLNGGSz
    url: jdbc:mysql://121.43.123.76:3306/shopwebdb?autoReconnect=true&autoReconnectForPools=true&noAccessToProcedureBodies=true&useunicode=true&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
#  type-aliases-package: com.example.demo.model
  mapper-locations: classpath:mybatis/mappers/*.xml